### ISSUE TITLE
Application hijacks Ctrl+F in parameter editor

### ISSUE THREAD

**Issue by Crack** [TouK/nussknacker#1022]
**Describe the bug**
Can't use Ctrl+F to search for value on page because Nussknacker displays its own search window:
![obraz](https://user-images.githubusercontent.com/1409807/86252293-52264000-bbb3-11ea-9557-fc3733f86a5a.png)

Firefox 77, latest demo

**Comment by Crack** [comment]
Looks like Ace editor search - https://ace.c9.io/

**Comment by lciolecki** [comment]
https://stackoverflow.com/questions/13677898/how-to-disable-ace-editors-find-dialog
