### ISSUE TITLE
Process sorting should be case insensitive

### ISSUE THREAD

**Issue by Crack** [TouK/nussknacker#1138]
**Describe the bug**
As in description, as a user I expect natural sorting of `a, A, z, Z` and not by ASCII code, which is what I get now: `A, Z, a, z`.

**To Reproduce**
Open process list, create a few processes, sort them.

**Comment by JulianWielga** [comment]
I'm not sure about this (there is some reason people write capitals), but I made PR #1144

**Comment by Crack** [comment]
@mproch @arkadius  whay do you think about this? My point is that when I see a list of values I expect it to be sorted the same way people do it, i.e. according to collation used by UI:
```
$ touch a ą A z Z
# computers do this:
$ LC_COLLATE=C ls
A  Z  a  z  ą
# people do this:
$ LC_COLLATE=en_US.utf8 ls
a  A  ą  z  Z
$ LC_COLLATE=pl_PL.utf8 ls
a  A  ą  z  Z
```
Or in another words: sort lists like they are in dictionaries.
