### ISSUE TITLE
Failed processes make process list replaced with big error message

### ISSUE THREAD

**Issue by Crack** [TouK/nussknacker#1139]
1. Open process list at https://staging.nussknacker.io/
2. Click around for a minute, wait until GUI sends request to https://staging.nussknacker.io/api/app/healthCheck/process/deployment
3. Serwer responds with HTTP 500: `{"status":"ERROR","message":"Deployed processes not running (probably failed)","processes":["foo","avrotest"]}`, process list is replaced with an error message:
![obraz](https://user-images.githubusercontent.com/1409807/89890566-e1237080-dbd3-11ea-8b2c-36802ec565a3.png)

**Comment by JulianWielga** [comment]
browser needed

**Comment by Crack** [comment]
* Firefox 79.0, 80.0b6
* Chrome 84.0.4147.125
