### ISSUE TITLE
Loose node causes validation errors with unhelpful message

### ISSUE THREAD

**Issue by piotrp** [TouK/nussknacker#1164]
**Describe the bug**
Having a loose node causes field validation to result in error message:
> The request content was malformed:
> Attempt to decode value on failed cursor: DownField(type),DownField(mapVarName),DownField(variableTypes)

**To Reproduce**
1. Go to https://demo.nussknacker.io/processes
2. Create new process
3. Add mapVariable and filter nodes, connect them
4. Open filter node

Instead of proper error message user sees:
![obraz](https://user-images.githubusercontent.com/1409807/91408387-15d62f80-e844-11ea-8292-54b447ba366e.png)

**Environment (please complete the following information):**
 - Nussknacker version: current demo, also 2020-08-17-11-29-preview_0_2_fixes-78f37a7fdfab01a20c604c3ccbbdb672c2e17c02-SNAPSHOT
 - Browser type and version: Firefox 80

**Comment by dswiecki** [comment]
@piotrp It looks as if this bug is not longer occurs however error tip message 'Loose node' is unhelpfull in this case
