### ISSUE TITLE
Can not Save and deploy my job by running in Idea.

### ISSUE THREAD

**Issue by MicDP** [TouK/nussknacker#12]
[ERROR] [05/17/2018 15:16:35.131] [nussknacker-ui-akka.actor.default-dispatcher-11] [akka.actor.ActorSystemImpl(nussknacker-ui)] Error during processing of request: 'Tcp command [Connect(localhost:8081,None,List(),Some(10 seconds),true)] failed because of 拒绝连接'. Completing with 500 Internal Server Error response. To change default exception handling behavior, provide a custom ExceptionHandler. (akka.stream.StreamTcpException)

And UI appears the tips ‘Properties: Failed to parse expression: Empty expression(param1)’

**Comment by raphaelsolarski** [comment]
Hello, 
Can you provide some additional information about the process you try to save/deploy?

**Comment by lciolecki** [comment]
I think it's this problem: 
![sample-param-error](https://user-images.githubusercontent.com/907665/70446796-eefd8080-1a9d-11ea-96f5-92c3fe2e7e7f.png)

Mayby we can set there default value '1'?

**Comment by lciolecki** [comment]
I've change default model configuration - now you needn't set this properties.
