### ISSUE TITLE
Invalid process status on process designer view after quick switch between processes. 

### ISSUE THREAD

**Issue by arkadius** [TouK/nussknacker#1240]
**To Reproduce**
- Click deploy on process A
- Switch view to process B
- After a while you will see status of process A instead of process B

Looks like some status change handler doesn't check if process id in message is the same as currently displayed process id.

**Comment by dswiecki** [comment]
@arkadius does it still occur ?

**Comment by arkadius** [comment]
Don't know, let's close this till we don't occur it in new implementation of status handling
