### ISSUE TITLE
GUI Issue - single-side-join component - component is broken when introducing a component an upper stream

### ISSUE THREAD

**Issue by mathieupedreropro** [TouK/nussknacker#1258]
Working with NK 0.2.2

I'm building a process relying on the outer-join component. 
![process_base](https://user-images.githubusercontent.com/68548830/95443375-c748a480-095c-11eb-94a3-626925632c44.png)
![outer_join_details](https://user-images.githubusercontent.com/68548830/95443374-c748a480-095c-11eb-904f-e692b43e4e0b.png)
When I try to introduce a component on one of the source stream of the outer-join component, the details panel of the outer-join component is broken 

![introducing_filter_component](https://user-images.githubusercontent.com/68548830/95443371-c6b00e00-095c-11eb-815f-4a4cd5e2114f.png)
![broker_outer_join_component](https://user-images.githubusercontent.com/68548830/95443369-c6177780-095c-11eb-9fdd-207aa9d768e1.png)

The branchTypecombobox field turns into a classic context field selection, an there is no other solution than removing the old outer join and create a brand new one from the toolbox.

Should you have any questions about this issue, please do not hesitate to contact me. 

Best regards,
-- 
Mathieu

**Comment by dswiecki** [comment]
@mathieupedreropro you can check version 1.1 this should be fixed there
