### ISSUE TITLE
No proper escaping for simple string editor

### ISSUE THREAD

**Issue by mproch** [TouK/nussknacker#1311]
**Describe the bug**
When using Simple String editor, we don't handle escaping properly which can be misleading

**To Reproduce**
In node with parameter with simple string editor (e.g. Template ID in configuratorService for DemoFeatures category) 
write "don't" -> it displays as invalid, as we create spel expression just by adding ' at the ends...  

**Environment (please complete the following information):**
staging version:  2020-11-13-23-25-staging-600b886bd3e2f256696f773452133f311de7be43

**Comment by lciolecki** [comment]
It was resolved by @JulianWielga on https://github.com/TouK/nussknacker/pull/1450/.
