### ISSUE TITLE
Issues with SQL highlighting

### ISSUE THREAD

**Issue by piotrp** [TouK/nussknacker#1494]
Version: current staging.

Sample query (a bit modified sample from staging):
```sql
WITH temp_table AS (
    SELECT
        a.srv_subscription_id AS subscription_id,
        to_char(sysdate, 'YYYY-MM-DD') AS char_date,
        max(a.id) AS max_id
    FROM
        test.test_table AS a
    WHERE a.date_field = #{#DATE.nowTimestamp}
)
SELECT
    a.srv_subscription_id AS subscription_id,
    a.char_date,
    rank() OVER (PARTITION BY subscription_id
                 ORDER BY char_date NULLS LAST
                 ROWS BETWEEN 1 PRECEDING AND 1 FOLLOWING)
FROM
    test.test_table AS a
WHERE a.date_field=#{#DATE.nowTimestamp}

```

With current highlighting looks like this:
![obraz](https://user-images.githubusercontent.com/1409807/112517748-f7fc8900-8d98-11eb-8731-ca38131485fb.png)

Issues:
* many unrecognized SQL keywords that can appear with window functions: PARTITION, ROWS, PRECEDING, FOLLOWING, UNBOUNDED, CURRENT ROW
* unrecognized SQL keywords  BETWEEN, NULLS, FIRST, LAST, THEN, DISTINCT, EXISTS, ANY, ALL, IN, FULL, USING, CAST, LIKE, ESCAPE, EXTRACT, ROLLUP, CUBE, GROUPING SETS, WITHIN
* inconsistent treatment of `subscription_id` column, once it's green, once white
* if I try to use a quoted identifier, eg `SELECT 12 AS "x" FROM dual`, syntax highlighting breaks
* button that switches between SQL and SpEL editor modes says "Switch to basic mode", regardless of current editor mode

SQL keyword lists I used as a reference:
* https://www.postgresql.org/docs/13/sql-keywords-appendix.html
* https://en.wikipedia.org/wiki/SQL_reserved_words

I'm not sure we should be using whatever the green color is used for, as currently it means three things: brackets for WITH, table aliases and column aliases - looks like a christmas tree, and IMO makes queries less readable. Maybe we shouldn't try so hard to color table/column aliases? It's impossible to do properly without proper lexical analysis.

**Comment by piotrp** [comment]
Examples from other editors:

VSCode
![obraz](https://user-images.githubusercontent.com/1409807/121486783-be1f4400-c9d1-11eb-97fb-6e3f63d31911.png)

IntelliJ IDEA
![obraz](https://user-images.githubusercontent.com/1409807/121486963-ea3ac500-c9d1-11eb-95fb-9f53e70053a1.png)

DBeaver
![obraz](https://user-images.githubusercontent.com/1409807/121487204-266e2580-c9d2-11eb-8e29-518f64edc0a2.png)

Oracle SQL Developer
![obraz](https://user-images.githubusercontent.com/1409807/121487327-46054e00-c9d2-11eb-8524-447c75d52651.png)

**Comment by mproch** [comment]
done
