### ISSUE TITLE
code completion (ux improvements)

### ISSUE THREAD

**Issue by witekw** [TouK/nussknacker#151]
Expression code completion should be proposed automatically, as new users won't be aware of the feature.

**Comment by arkadius** [comment]
I've added PR resolving it. Will be available as a preview on https://demo.nussknacker.io/ after build completion: https://travis-ci.org/TouK/nussknacker/builds/593869516

**Comment by witekw** [comment]
Thank you!

**Comment by arkadius** [comment]
u'r welcome :)
