### ISSUE TITLE
ERROR: for docker_jobmanager_1  Cannot start service jobmanager: oci runtime error: container_linux.go:247: starting container process caused "exec: \"/run.sh\": permission denied"

### ISSUE THREAD

**Issue by xuguangzhao** [TouK/nussknacker#16]
hi,

when i deploy the demo/docker example ,  but when I  docker-compose up : is oci runtime error
ERROR: for docker_jobmanager_1  Cannot start service jobmanager: oci runtime error: container_linux.go:247: starting container process caused "exec: \"/run.sh\": permission denied"

![1535105315 1](https://user-images.githubusercontent.com/40658303/44579427-ff1a1f80-a7c8-11e8-82aa-1e58f9388402.png)

**Comment by mproch** [comment]
Hi @xuguangzhao. I understand you use latest master version? Which docker version are you using - and on what OS? We haven't tested on windows as we don't have necessary resources...

**Comment by lciolecki** [comment]
We have released new version of application where we have changed and updated demo example. You can test it now.
