### ISSUE TITLE
show information about backends available for process category (FE)

### ISSUE THREAD

**Issue by witekw** [TouK/nussknacker#169]

**Comment by mproch** [comment]
it works other way round - backend is determined by category

**Comment by witekw** [comment]
Acknowledged, do you think it would help user to see which backend is he writing for? I assume there would be different components in the creator panel which could be confusing?

**Comment by lciolecki** [comment]
It's releated with https://github.com/TouK/nussknacker/issues/156. After that we can return additional information about model assigned to category.
