### ISSUE TITLE
Quickstart - Error while reporting metrics 

### ISSUE THREAD

**Issue by PiotrBabol** [TouK/nussknacker#17]
Hi. 

I'm running  docker-compose up as it says in the quickstart guide, however it  seems to have an issue with starting the nussknacker service properly. Kibana , grafana and flink web services are up and running , but nussknacker returns 502. 

I'm not sure, but I belive it has something to do with Error that comes up when I run docker compose.
The log below just repeats itself until I "ctrl+c" it :)

I tried fixing this with substituting flink-metrics-graphite-1.2.0.jar with the newer flink-metrics-graphite-1.6.0.jar, but it didn't help :)

> nginx_1          | 172.18.0.1 - - [20/Sep/2018:08:13:36 +0000] "GET /flink/joboverview HTTP/1.1" 200 28 "http://localhost:8081/flink/" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0"
nginx_1          | 172.18.0.1 - - [20/Sep/2018:08:13:39 +0000] "GET /flink/joboverview HTTP/1.1" 200 28 "http://localhost:8081/flink/" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0"
jobmanager_1     | 2018-09-20 08:13:40,456 WARN  org.apache.flink.runtime.metrics.MetricRegistryImpl           - Error while reporting metrics
jobmanager_1     | java.nio.channels.UnresolvedAddressException
jobmanager_1     | 	at sun.nio.ch.Net.checkAddress(Net.java:101)
jobmanager_1     | 	at sun.nio.ch.DatagramChannelImpl.send(DatagramChannelImpl.java:429)
jobmanager_1     | 	at com.codahale.metrics.graphite.GraphiteUDP.send(GraphiteUDP.java:90)
jobmanager_1     | 	at com.codahale.metrics.graphite.GraphiteReporter.reportGauge(GraphiteReporter.java:270)
jobmanager_1     | 	at com.codahale.metrics.graphite.GraphiteReporter.report(GraphiteReporter.java:158)
jobmanager_1     | 	at org.apache.flink.dropwizard.ScheduledDropwizardReporter.report(ScheduledDropwizardReporter.java:230)
jobmanager_1     | 	at org.apache.flink.runtime.metrics.MetricRegistryImpl$ReporterTask.run(MetricRegistryImpl.java:417)
jobmanager_1     | 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
jobmanager_1     | 	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
jobmanager_1     | 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
jobmanager_1     | 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
jobmanager_1     | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
jobmanager_1     | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
jobmanager_1     | 	at java.lang.Thread.run(Thread.java:748)
nginx_1          | 172.18.0.1 - - [20/Sep/2018:08:13:42 +0000] "GET /flink/joboverview HTTP/1.1" 200 28 "http://localhost:8081/flink/" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0"
taskmanager_1    | 2018-09-20 08:13:42,714 WARN  org.apache.flink.runtime.metrics.MetricRegistryImpl           - Error while reporting metrics
taskmanager_1    | java.nio.channels.UnresolvedAddressException
taskmanager_1    | 	at sun.nio.ch.Net.checkAddress(Net.java:101)
taskmanager_1    | 	at sun.nio.ch.DatagramChannelImpl.send(DatagramChannelImpl.java:429)
taskmanager_1    | 	at com.codahale.metrics.graphite.GraphiteUDP.send(GraphiteUDP.java:90)
taskmanager_1    | 	at com.codahale.metrics.graphite.GraphiteReporter.reportGauge(GraphiteReporter.java:270)
taskmanager_1    | 	at com.codahale.metrics.graphite.GraphiteReporter.report(GraphiteReporter.java:158)
taskmanager_1    | 	at org.apache.flink.dropwizard.ScheduledDropwizardReporter.report(ScheduledDropwizardReporter.java:230)
taskmanager_1    | 	at org.apache.flink.runtime.metrics.MetricRegistryImpl$ReporterTask.run(MetricRegistryImpl.java:417)
taskmanager_1    | 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
taskmanager_1    | 	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
taskmanager_1    | 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
taskmanager_1    | 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
taskmanager_1    | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
taskmanager_1    | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
taskmanager_1    | 	at java.lang.Thread.run(Thread.java:748)
nginx_1          | 172.18.0.1 - - [20/Sep/2018:08:13:45 +0000] "GET /flink/joboverview HTTP/1.1" 200 28 "http://localhost:8081/flink/" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0"
nginx_1          | 172.18.0.1 - - [20/Sep/2018:08:13:48 +0000] "GET /flink/joboverview HTTP/1.1" 200 28 "http://localhost:8081/flink/" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0"

... and it just goes on

**Comment by lciolecki** [comment]
We have released new version of application where we have changed and updated demo example. You can test it now.
