### ISSUE TITLE
cannot access error descriptions

### ISSUE THREAD

**Issue by witekw** [TouK/nussknacker#179]
![image](https://user-images.githubusercontent.com/632221/66309666-7d248180-e90a-11e9-98d9-d1012b33f59a.png)

It would be easy to show more meaningful message (already available)

![image](https://user-images.githubusercontent.com/632221/66309755-b1983d80-e90a-11e9-80bd-f5aa98d5def5.png)

**Comment by witekw** [comment]
Also we have information that node0 is in an error state. IMHO this shoud be shown directly in the diagram (e.g. icon, border, background).

**Comment by witekw** [comment]
I think after completing #233 redesign is needed, options:

- delete this panel at all
- change to list of errors linking to the element that caused the problem
- change to a summary of errors

I would ask users some time after releasing #233

**Comment by lciolecki** [comment]
I think we can already close this issue.
