### ISSUE TITLE
What is "Business view" for? How does it work?

### ISSUE THREAD

**Issue by witekw** [TouK/nussknacker#181]

**Comment by mproch** [comment]
The idea is to be able to show what process does (i.e. business logic) without technical details.
https://github.com/TouK/nussknacker/blob/master/ui/server/src/main/scala/pl/touk/nussknacker/ui/process/marshall/ProcessConverter.scala#L52 -> here is the heart of hiding 'technical' details - that is, we don't show enrichers and variables. 

We're not sure if this feature is currently widely used - we may discuss changing/removing it

**Comment by lciolecki** [comment]
Explained :)
