### ISSUE TITLE
retesting process should not require to select test data

### ISSUE THREAD

**Issue by witekw** [TouK/nussknacker#182]
Please consider separating uploading of test data and triggering tests. I think you usually run tests many times using the same data. It would save users time.

**Comment by witekw** [comment]
More ambitious option is to store test data along with a process.

**Comment by lciolecki** [comment]
Mayby we can store them in locastorage?

**Comment by witekw** [comment]
I've made a task  #330 to rebuild "testing panel", its more general task than this one. I like the idea for users to share test data - it could encourage testing.

**Comment by lciolecki** [comment]
Okey, so we can close this ticket @witekw ?

**Comment by witekw** [comment]
yes, #330 covers this usecase
