### ISSUE TITLE
sliding panels UX

### ISSUE THREAD

**Issue by witekw** [TouK/nussknacker#184]
- they look coarse, there are better ways (handle bars)
- right one could be reactive

**Comment by ppd-touk** [comment]
@witekw Can you provide some examples of what you mean by "reactive"?
What kind of changes should be made?

**Comment by witekw** [comment]
Should be "responsive", see https://uxdesign.cc/handlebars-in-ui-design-4b36af67733b

**Comment by lciolecki** [comment]
@JulianWielga now is doing this in https://github.com/TouK/nussknacker/issues/702. So I think we can close it?
