### ISSUE TITLE
Invalid escape'ing of process name in URLs - cannot rename/open process

### ISSUE THREAD

**Issue by piotrp** [TouK/nussknacker#1880]
Version: current staging

# Bug 1

Create/rename process so that its name contains `/`

Effect after adding `/` to process name in Chrome, after clicking _save_:
![obraz](https://user-images.githubusercontent.com/1409807/124490424-5a125480-ddb2-11eb-9e02-eb41f0ff9025.png)
Process wasn't saved.

# Bug 2

Process with `|` in its name cannot be open in Firefox, eg. `DSW|DSW` on staging. Works in Chrome. Renaming a process to contain `|` in its name also fails.

**Comment by dswiecki** [comment]
Fixed in #2759
