### ISSUE TITLE
Undoing node paste requires to use "undo" three times

### ISSUE THREAD

**Issue by piotrp** [TouK/nussknacker#1881]
**Describe the bug**
When I paste a node from clipboard and want to undo it I need to press undo / Ctrl+Z three times. Pasting also reformats displayed graph.

**To Reproduce**
Go to https://staging.nussknacker.io/visualization/FeaturesTest , copy last node and paste it.

![Animation](https://user-images.githubusercontent.com/1409807/124492610-fdfcff80-ddb4-11eb-89a5-3b07099bad62.gif)

**Environment**
Current staging.
Chrome 91 / Firefox 89.

**Comment by dswiecki** [comment]
fixed in #3881 and #3884
