### ISSUE TITLE
readonly fields are indistinguishable from editable ones

### ISSUE THREAD

**Issue by witekw** [TouK/nussknacker#192]
![image](https://user-images.githubusercontent.com/632221/66350682-437c6680-e95c-11e9-872f-2da83736d02c.png)

"Ref Type" in the above case

**Comment by arkadius** [comment]
This problem still exists in many places:
- in compare modal
- in grouped nodes details modal

Some fields are distinguishable like id, node type in "compare modal" but other are not like: expression editor or area input (used in description)

**Comment by arkadius** [comment]
There are still problems:

- checkboxes not change background
- simple/raw editor switcher not changes style
- some other fields not changes style: description, some other fields in compare
