### ISSUE TITLE
Deployment via API cancels running scenario despite new version being invalid

### ISSUE THREAD

**Issue by piotrp** [TouK/nussknacker#1988]
**Describe the bug**
When deploying via POST to `/api/processManagement/deploy/{scenario name}` Nussknacker cancels running scenario before checking whether new one can be deployed, making it possible to break live environment by trying to run an automated redeployment of all scenarios.

**To Reproduce**
1. Create and deploy a scenario
2. Change scenario to be invalid
3. Send POST to `/api/processManagement/deploy/{scenario name}`

Running scenario will be cancelled, and API will return an error:

> Flink cluster failed to deploy scenario. Detailed error information in logs

I have two issues with this:
1. API shouldn't cancel running scenario if it's impossible to deploy a new version due to validation errors
2. It's NK that cannot deploy, Flink has nothing to do with this

**Environment**
 - Nussknacker: staging@360bcb1b775e384de9cf2d11af15fcbbca72eb02

**Comment by dswiecki** [comment]
Probably fixed in #3392

**Comment by gadomsky** [comment]
That's right. It has been fixed. I close the issue.
