### ISSUE TITLE
Quickstart running failed

### ISSUE THREAD

**Issue by yew1eb** [TouK/nussknacker#2]
I follow the quickstart after installing and running,
 (https://touk.github.io/nussknacker/Quickstart.html)

but, I check:
Nussknacker  failed {open link: http://localhost:8081/  return: 502 Bad Gateway}
Apache Flink ui   ok
Grafana    ok
Kibana    ok

Who can help me?

regards,
Hai Zhou

**Comment by yew1eb** [comment]
Hi @mproch , @fijolekProjects , @coutoPL @arkadius,
log file: [nussknacker-log.txt](https://github.com/TouK/nussknacker/files/1280230/nussknacker-log.txt)

regards,
Hai Zhou

**Comment by clutroth** [comment]
Hi, thanks for bug report Please run `./getSampleAssembly.sh 0.0.6`. We will add it to docs.

**Comment by yew1eb** [comment]
thanks for your reply.
BTW, nussknacker project is really cool! :simple_smile:

**Comment by fijolekProjects** [comment]
Hi @yew1eb. Did you manage to run quickstart?

**Comment by ocet** [comment]
Hello. I encountered following issue during quickstart: 
```
$ docker-compose up
ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a version of "2" (or "2.0") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/
```

After replacing 
`version: '2.1'` with `version: '2'` in `docker-compose.yml` it runs and builds images.

Another error follows:
```
$ docker-compose up
# ...
ERROR: for app Cannot start service app: oci runtime error: container_linux.go:262: starting container process caused "exec: \"/bin/sh\": stat /bin/sh: no such file or directory"
```

Installation enviroment being clean VBox with Lubuntu 17.04 LTS. Additional info:
```
$ uname -a
Linux lubuntu-VirtualBox 4.10.0-19-generic #21-Ubuntu SMP Thu Apr 6 17:04:57 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

$ docker -v
Docker version 17.07-ce, build 

$ docker info
Containers: 12
 Running: 0
 Paused: 0
 Stopped: 12
Images: 32
Server Version: 17.07.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 137
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 3addd840653146c90a254301d6c3a663c7fd6429
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.10.0-19-generic
Operating System: Ubuntu 17.04
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.949GiB
Name: lubuntu-VirtualBox
ID: LI2M:6RHK:HL5O:ZD5P:KMAT:FTG6:YUPR:P4KE:S242:SBBQ:V634:FMF3
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
 
WARNING: No swap limit support
```
By the way, this project looks great. Can't wait to get my hands on it.

**Comment by clutroth** [comment]
Hi @ocet,
please check if `/tmp/code-assembly.jar` is file or directory. Have you configured Docker to work without sudo? 
`https://docs.docker.com/engine/installation/linux/linux-postinstall/`

**Comment by ocet** [comment]
@clutroth 
Thank you for your response. 

`/tmp/code-assembly.jar` exists and user is configured to use docker w/o sudo. Ill shred the VM and try again with different docker installation.
