### ISSUE TITLE
empty "creator panel"

### ISSUE THREAD

**Issue by witekw** [TouK/nussknacker#206]
**Describe the bug**
There are no items In the "creator panel". Categories are shown properly.

**To Reproduce**
1. https://demo.nussknacker.io/
2. edit any process

**Screenshots**

![image](https://user-images.githubusercontent.com/632221/66735307-4c8e9b80-ee66-11e9-94bb-b1126762fbe3.png)

**Comment by ppd-touk** [comment]
Given request: "/api/processDefinitionData/streaming?isSubprocess=false" 
returns response with empty array in JSON property: nodesToAdd.possibleNodes.categories

This fact results in situation when (empty) categories array does not include process category (f.e. "Default") which implies that nodesToAdd.possibleNodes are overriden with empty array and not displayed.

Is this sort of backend problem?

**Comment by bottaio** [comment]
Yeah, this is indeed a backend problem. It's related to our new permissions system. I'll fix it by the end of the day.
