### ISSUE TITLE
add "copy", "paste", "cut" options to "edit"

### ISSUE THREAD

**Issue by witekw** [TouK/nussknacker#207]
Putting these commands into menu would show they are available. Now you have to know about keyboard shortcuts.

**Comment by mproch** [comment]
won't it make edit part too clumsy

**Comment by ppd-touk** [comment]
Aren't this commands actually most important ones?

**Comment by arkadius** [comment]
I agree with both of yours. What do you think about making some UX analysis before we will done this task?

**Comment by witekw** [comment]
We should choose design language (https://en.wikipedia.org/wiki/Design_language) and stick to it.

We can make buttons and the underlying mechanics now and decide wheather it should be buttons or some context menu near selected element later.
