### ISSUE TITLE
Ok button in Deploy/Cancel confirmation modal is wrongly positioned

### ISSUE THREAD

**Issue by gadomsky** [TouK/nussknacker#2072]
**Describe the bug**
Ok button in Deploy confirmation modal is wrongly positioned

**To Reproduce**
Click deploy/cancel

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04
 - Nussknacker version 0.4
 - Browser type and version  chrome

**Comment by mproch** [comment]
fixed with #1706
