### ISSUE TITLE
Moved node is shown as changed in "compare versions"

### ISSUE THREAD

**Issue by piotrp** [TouK/nussknacker#2109]
Reported by customer.

**Describe the bug**
"compare" button detects nodes that changed their position on canvas as changed, so nodes with no meaningful changes are shown in "Difference to pick list"

![obraz](https://user-images.githubusercontent.com/1409807/131843441-764c7659-c044-4704-b824-296abc5e7ae3.png)

**To Reproduce**
1. Move node
2. Save changes
3. Click "compare"

**Environment (please complete the following information):**
 - Nussknacker: current staging
 - Browser: Firefox 91

**Comment by dswiecki** [comment]
@piotrp done in #2663
