### ISSUE TITLE
Deploy previously saved version

### ISSUE THREAD

**Issue by ppd-touk** [TouK/nussknacker#213]
It would be a nice feature to be able to "Deploy" a previously saved version.

**Comment by mproch** [comment]
What would this feature do?

**Comment by lciolecki** [comment]
But you can rollback to previous version and do deploy?

**Comment by ppd-touk** [comment]
I've splitted issue reported by @witekw.
Please ask @witekw for more details

**Comment by witekw** [comment]
Scenario is:
- a process is deployed
- user changes the process
- changes are significant WiP and do not work yet
- user has to rollback to previous version to fix some bug
- he looses changes

I know the workaround is to export process and then import as a new one. If "versions" are enough to achieve this user would gain from version "comparison" feature.
