### ISSUE TITLE
Red-face with three clicks

### ISSUE THREAD

**Issue by Filemon279** [TouK/nussknacker#2186]
**Describe the bug**
Red face appears on the whole page after pressing 3 times Ctrl+z while editing node. 

**To Reproduce**
- Open any process
- Open any node and click anywhere but on editing fields. 
![image](https://user-images.githubusercontent.com/13632953/133102671-64dd3041-9a02-4d73-a468-0465c0a55063.png)
- Press three times CTRL + Z.

![image](https://user-images.githubusercontent.com/13632953/133103007-8e231bf2-b825-4dec-96d0-3dfbda0b1b34.png)

**Environment:**
 - OS: Ubuntu 21.04
 - Staging
 - chrome 91

**Comment by mproch** [comment]
fixed via #2195
