### ISSUE TITLE
Bug on change switch edge with condition

### ISSUE THREAD

**Issue by lciolecki** [TouK/nussknacker#2235]
**Describe the bug**
When we want to move / change edge destination from one node to another then edge lost their condition

**To Reproduce**
Steps to reproduce the behavior.

1. Create source
2. Create switch node
3. Create two sinks
4. On one edge to sink add some condition, eg. #input != null
5. Create third sink
6. Move edge with condition to third sink <- condition should be lost

**Comment by dswiecki** [comment]
Fixed in #3091
