### ISSUE TITLE
processes page

### ISSUE THREAD

**Issue by witekw** [TouK/nussknacker#230]
"process name" in table header -> name
  sorting by category -> add secondary sort by name
  last modification -> use relative time (momentjs?)

**Comment by PPiedel** [comment]
Library used to display tables ("reactable") does not support multi-sorting. There are open issues on Github: https://github.com/glittershark/reactable/issues/376, https://github.com/glittershark/reactable/issues/309 but it does not seem that they will make these changes.
Multisort is available in "react-table" - but librabry change is much more work to do. We should consider if multisort is worth of it.

**Comment by witekw** [comment]
Not worth it now.

**Comment by witekw** [comment]
Maybe it is enough if the backend returns data sorted by category, name to initialize the table?
