### ISSUE TITLE
Timezone should be included in returned dates

### ISSUE THREAD

**Issue by PPiedel** [TouK/nussknacker#231]
Currently date is returned without information about time zone, f.e.:
`"modificationDate":"2019-10-08T09:36:40.828"`

**Expected behavior**
Timezone information should be included.

**Comment by witekw** [comment]
This will break formatting on the frontend:

export default {
  format(dateTimeString) {
    //TODO: something better?
    return dateTimeString.replace("T", " | ").substring(0, 18)
  }
}

Can we try using ~momentjs and format to both absolute and relative time? We could use relative time on process list.
