### ISSUE TITLE
show params validation error in the context of params

### ISSUE THREAD

**Issue by witekw** [TouK/nussknacker#233]
![image](https://user-images.githubusercontent.com/632221/67080244-1702ee80-f195-11e9-8776-953876285599.png)

Instead of showing "Field param2 (Required param - text) cannot be empty (field: param2)" at the top:

1. emphasize "Required param - text:" input field with orange border
2. display message or description below the input field

**Comment by witekw** [comment]
After completing this issue please consider calling "/api/processValidation" during properties edit, so users get feedback about error earlier.

**Comment by arkadius** [comment]
We can consider if we should use (ace/brace) errors indicator visible here: https://thlorenz.com/brace/
It will be nice if calling of api would be debounced during typing. Also we car return position range of error in api so we can underscore exact place of error

**Comment by arkadius** [comment]
It is connected with: https://github.com/TouK/nussknacker/issues/249 ... During typing, type of expression can change, also errors can block inferring this type

**Comment by PPiedel** [comment]
We also need to return field name for each validation error - now not all responses contain such a name.
Should we create separate issue for that?

**Comment by witekw** [comment]
Can we make this change gradually?

- show errors/warnings near parameters when possible (GUI work only)
- improve on error reporting in API returns (#179)
- introduce dynamic validation (e.g. before node properties save on focus change)

**Comment by witekw** [comment]
Consistent style to indicate errors (new issue?)
