### ISSUE TITLE
Quick jump to process metrics

### ISSUE THREAD

**Issue by witekw** [TouK/nussknacker#238]
1. return from process metrics is not consistent
process edit -> metrics -> back (to the process)
process list -> metrics -> back (to the process)

2. indication that we are in a context of a process looks bad
![image](https://user-images.githubusercontent.com/632221/67099202-cc499c80-f1bd-11e9-98aa-8bb72dce5433.png)

Proposal: ask users and remove this feature

**Comment by witekw** [comment]
Altertative: open metrics in a new window, get rid of the arrow

**Comment by lciolecki** [comment]
It's duplication of https://github.com/TouK/nussknacker/issues/856
