### ISSUE TITLE
[BUG][UI] Rendering docsUrl

### ISSUE THREAD

**Issue by gadomsky** [TouK/nussknacker#2401]
**Describe the bug**
* When rendering `NodeDetailsModalHeader` after entering any node's `NodeDetailsModal` directly via the link, the `docsUrl` is pointing always to `Properties` node's `docsUrl`
* When selecting any node on graph, and then opening `Properties`, the `docsUrl` is pointing to that selected node's from the graph `docsUrl` instead of `Properties` node's `docsUrl`

**Comment by lciolecki** [comment]
Right now it's fixed, I have tested it on staging.
