### ISSUE TITLE
Showing inferred expression type

### ISSUE THREAD

**Issue by arkadius** [TouK/nussknacker#249]
Would be nice if somewhere near expression will be shown type of inferred expression. Especially it will be helpful when someone define new variable and didn't know that inferred expression's type is unknown. This can produce a lot of errors in expressions using this variable.

This type can be shown only for validated processes.

**Comment by witekw** [comment]
Shall we show it in the same way as parameter types under the label "Expression"?

![image](https://user-images.githubusercontent.com/632221/67776088-1f460e00-fa60-11e9-86e8-655bc395f66c.png)

![image](https://user-images.githubusercontent.com/632221/67776111-2705b280-fa60-11e9-8710-a9b0ce3fdf70.png)

Where do you plan to return this information (process API endpoint)?
Will it be available before saving the process?

**Comment by arkadius** [comment]
Yes, IMO it may be presented the same way as parameter type.
We return it in validation result, in `variableTypes` field. When we will add validation in context of node, it will be simpler to extract this type, but for now it is also possible.

**Comment by arkadius** [comment]
After thinking a while, presenting this information exactly like in parameter type can be confusing.
User may think that it is declared type, not inferred type. Declared type that he or she can't change and expression must produce the same type.
I think that the place may be right, but we need to think how to make it less ambiguous... Any idea? Maybe some little icon :information_source: with tooltip that the type is inferred?

**Comment by arkadius** [comment]
Notice: At first step we can update it only after validation of process (closing modal and going back to them). But eventually it should be updated live during coding of expression

**Comment by fi-** [comment]
It should look like this:
![inferredtype](https://user-images.githubusercontent.com/8850099/72062240-affa5f00-32d7-11ea-828e-0ce871d0c6a3.jpg)
height: 18px
bg color: #292929 
text color: #808080
text color (type): ideally every type could have a corresponding color, but on default we can stick with #6a8759 
font: consolas regular
the box should stretch to message width

for now we can't display inferred type in real time so meanwhile we will display an alternative message when we can't display the type yet.

**Comment by nadberezny** [comment]
Resolved with:
https://github.com/TouK/nussknacker/pull/1191
https://github.com/TouK/nussknacker/pull/1222
