### ISSUE TITLE
[v1.0.0] Can't build on local

### ISSUE THREAD

**Issue by magicLian** [TouK/nussknacker#2531]
pl.touk.nussknacker.engine.version.BuildInfo not found

**Comment by magicLian** [comment]
./nussknacker/ui/server/src/main/scala/pl/touk/nussknacker/ui/api/AppResources.scala:15:35
object version is not a member of package pl.touk.nussknacker.engine
import pl.touk.nussknacker.engine.version.BuildInfo

**Comment by arkadius** [comment]
How you try to build? using sbt or IDE? If u using Intellij Idea, you need to perform one manual step via cmd - execute `sbt buildInfo`. After this, everything should compile.

**Comment by magicLian** [comment]
Sorry for that,  im trying to run it on my machine using IDEA and now i could compile and package it  via cmd `sbt clean compile package`. 

But an error occurs by debuging with IDEA,  error is :

ProcessConfigCreator not found. Jars found: file:/home/lz/workspace/nussknacker/ui/server/work/../../../engine/standalone/engine/sample/target/scala-2.12/standaloneSample.jar

I did not modify file `/home/lz/workspace/nussknacker/.run/NussknackerApp.run.xml`  and i could found the `/home/lz/workspace/nussknacker/engine/standalone/engine/sample/target/scala-2.12/nussknacker-standalone-sample_2.12-1.0.0.jar`

Im confusing...

**Comment by arkadius** [comment]
Yeah, we will try to fix that this step won't be needed: https://youtrack.jetbrains.com/issue/SCL-18993

Regards to second problem, in `ui/README.md` there is a little instruction how to run project via Idea. You need to perform second manual step `cd ui; ./buildServer.sh` - it will build fat jars with our plugins (components and deployment managers).

**Comment by magicLian** [comment]
Thx man, it runs successfully now.
