### ISSUE TITLE
archived process view - enabled options in panels

### ISSUE THREAD

**Issue by witekw** [TouK/nussknacker#256]
Archived processes can be viewed only, so most of the tools should be disabled or maybe even not shown at all i.e.

right panel: save, import, archive, undo, redo, cut, paste, copy, delete, duplicate, all test buttons
node details: all input boxes should be disabled or simpler "view mode" introduced
left panel: components should not be draggable
processValidation should not be called at all, though maybe it's not a case if above are disabled

**Comment by mproch** [comment]
this seems like regression :/
