### ISSUE TITLE
Editor for schedules (cron expressions)

### ISSUE THREAD

**Issue by witekw** [TouK/nussknacker#260]
Please validate cron expressions or better provide a simple (but not limining) expression builder in UI so users do not need to consult manuals.

![image](https://user-images.githubusercontent.com/632221/67697512-f4e54980-f9a8-11e9-9e77-1621db512436.png)

**Comment by arkadius** [comment]
Spel expressions: `T(com.cronutils.parser.CronParser).parse(' 23 * ? * 1-5 *')`
