### ISSUE TITLE
Field names in validation response

### ISSUE THREAD

**Issue by PPiedel** [TouK/nussknacker#268]
In some cases "fieldName" in "errors.invalidNodes" is returned as null (f.e. for "Expression" field), even when it's connected with specific field.
1.We should fill fieldName, whenever it's possible.
2. "fieldName" for branch parameters is returned in form "parameterName for branch branchName". It's enough to return it in the form of "parameterName-branchName"

This issue is related to #233.

**Comment by PPiedel** [comment]
There is also sort of strange situation.
Edge validation responses are returned as if edge was "from" node. 
It is to be considered whether this should be improved

**Comment by PPiedel** [comment]
Another thing.
Validation responses of MapVariable node contains ExpressionParseErrors which are in fact related to field value, but the fieldName property of JSON response are filled as they were related to field key. Please fix it.

**Comment by witekw** [comment]
![image](https://user-images.githubusercontent.com/632221/68946799-1f5e4180-07b4-11ea-9260-4666528197bf.png)

**Comment by witekw** [comment]
New tasks with missing cases will be created.
