### ISSUE TITLE
Creating scenarios with some special characters results in an error

### ISSUE THREAD

**Issue by piotrp** [TouK/nussknacker#2755]
Try to create a scenario containing one of these characters: `[]/?#`.

Result: application displays an error message:

![obraz](https://user-images.githubusercontent.com/1409807/150144107-be7770a8-dffb-4c08-8bcc-3b8f2c2ba326.png)

Version: current staging

**Comment by dswiecki** [comment]
Fixed in https://github.com/TouK/nussknacker/pull/2759
