### ISSUE TITLE
Linking to nodes with some special characters is broken

### ISSUE THREAD

**Issue by piotrp** [TouK/nussknacker#2756]
1. Create a node having one of these characters on its name: `[],#`
2. Find this node in Components tab
3. Click on component instance link

Result: browser shows an error message ("Illegal request-target: Invalid input...") or loads scenario without opening requested node (behavior differs depending on used character).

There's also a similar issue with comma alone in scenario designer - when I open a node with `,` in its name and press F5 the application reloads but doesn't reopen this node's edit window.

Version: current staging

**Comment by dswiecki** [comment]
Fixed in https://github.com/TouK/nussknacker/pull/2759
