### ISSUE TITLE
chmod -R ug+wr ${STORAGE_DIR}/* needed? Issues in Azure deployment

### ISSUE THREAD

**Issue by an0r0c** [TouK/nussknacker#2929]
Hi!

I tried to deploy nussknacker to an azure AKS cluster. And had some issues with that 
`chmod -R ug+wr ${STORAGE_DIR}/*`
in the dockerfile. 

per default a new disk on azure has a "lost+found" folder  (`${STORAGE_DIR}/lost+found`) and there are missing permissions to chmod this folder. 

Is this `/*` needed?  Wouldn't a `chmod -R ug+wr ${STORAGE_DIR}/db` be sufficient?

https://github.com/TouK/nussknacker/blob/824d857ebd334716d2aecd5748260c0064eb5e36/nussknacker-dist/src/universal/bin/nussknacker-entrypoint.sh#L21

Thanks, BR 
Christian

**Comment by mproch** [comment]
Hi, 
we can also use this folder to store attachments for scenarios, but yes, probably we can modify this chmod to affect only needed subfolders.
In the meantime, I wonder if configuring 
```
persistence:
   subpath: "something"
``` 
would work as a workaround?

**Comment by an0r0c** [comment]
Hi, 

seems not to help. 

Im just thinking that a "-f" would fix it with the risk that some real issue get hidden later on. 

or explicitly just chown storage dir +  the db dir (as the db dir is the only dir/file in there atm as the db folder got created just before)

Would you be fine with one of those variants? I can provide a PR with that change

**Comment by mproch** [comment]
Hi @an0r0c,
In the end we removed chmod altogether - turned out it was some old docker setup. We also backported it to our 1.2 branch - you can try docker tag release_1.2-latest:
https://hub.docker.com/layers/touk/nussknacker/release_1.2-latest/images/sha256-a2958f8ef8c13cb7f1fd3c36816233e713adba14d392afdea244a4f0c7684967?context=explore

**Comment by an0r0c** [comment]
Hi, sorry for quite late response was quite busy last week.
I can verify that it works now with persistence enabled. 

Thx!
