### ISSUE TITLE
creator panel - fix vertical centering

### ISSUE THREAD

**Issue by fi-** [TouK/nussknacker#302]
Przed:
![2019-11-07 14_45_29-Nussknacker](https://user-images.githubusercontent.com/8850099/68395434-fdd7d700-016f-11ea-94b1-909e69a78a45.png)

Po:
![2019-11-07 15_01_45-Nussknacker](https://user-images.githubusercontent.com/8850099/68395455-04fee500-0170-11ea-8754-9d24556bb637.png)

**Comment by lciolecki** [comment]
@fi- can we close it?

**Comment by lciolecki** [comment]
It's already done.
