### ISSUE TITLE
Back action in browser on scenario view with open node causes popup with "The broken nut"

### ISSUE THREAD

**Issue by raphaelsolarski** [TouK/nussknacker#3058]
**Describe the bug**
After using back action in browser when scenario node dialog was open, NU shows dialog with "The broken nut on red background" for a moment.

**To Reproduce**
1. Open some scenario from scenarios list.
2. Open some node in scenario.
3. Click back in your browser.

**Environment:**
 - Nussknacker version: 1.4.0-staging-2022-05-13-7475-f8a2922406427861281d0
09983bc68097407780c-SNAPSHOT
 - Browser: Chrome Version 101.0.4951.64 (Official Build) (arm64)
 
 <img width="958" alt="Screenshot 2022-05-13 at 14 44 06" src="https://user-images.githubusercontent.com/12599369/168285624-5b0ccca2-24ea-4e2b-bd90-f422cb51c610.png">

**Comment by dswiecki** [comment]
Fixed in #3105 @raphaelsolarski thanks for noticing
