### ISSUE TITLE
Error message disappears after 1 sec

### ISSUE THREAD

**Issue by gskrobisz** [TouK/nussknacker#3062]
**Describe the bug**
Error message "invalid end of process" inside filter component disappears after 1sec.
 
Example:
https://staging.nussknacker.io/visualization/gsk

**To Reproduce**
1. Create scenario with source and a filter component
2. Add two sinks after filter, and connect to filter.
3. So far all components are validated correctly, there are two edges going out of the filter: "true" and "false".
4. Delete sink with "true" on the filter-sink edge
5. Edge with "false" changes to condition to "true" (and this is ok)
6. Filter component is red, component displays error message "invalid end of process" which disappears after ~1 sec.

**Environment:**
1.4.0-staging-2022-05-16-7483-41ed5f8909a4836d8a7bd525139ee935cb7337ca-SNAPSHOT
FF 101.0b7
Chrome v100

**Comment by dswiecki** [comment]
@gskrobisz please check right now but I think bug no longer occurs
