### ISSUE TITLE
Redesign of test panel

### ISSUE THREAD

**Issue by witekw** [TouK/nussknacker#330]
![image](https://user-images.githubusercontent.com/632221/68473434-3f758a00-0223-11ea-8e7f-6ed30d496e2b.png)

"Test" panel

- test data sets would be attached to the process
- you can run predefined test set easily (play icon), counts are shown
- you can rename, download, delete a test set
- you can rename existing test set
- you can generate new test data set (could not find icon)
- you can hide counts

"Monitoring" panel

- quick access to predefined times
- pressing play retrieves and shows counts
- you can hide counts
- you can enable auto-reload

**Comment by mproch** [comment]
Will be done during test rework
