### ISSUE TITLE
numbers attached to nodes in test view and counts view can look better

### ISSUE THREAD

**Issue by fi-** [TouK/nussknacker#331]
it should look like this:
![counts3](https://user-images.githubusercontent.com/8850099/69041717-41dc9e80-09f0-11ea-927e-027b843cad97.png)

bg color: #4d4d4d
text color: #ccc
font size on default zoom: 16px
padding on default zoom: 8px

this is how they look now:
![Clipboard - November 8, 2019 12_45 PM](https://user-images.githubusercontent.com/8850099/68474561-fecb4000-0225-11ea-8901-d02f9921ffd2.png)

**Comment by witekw** [comment]
There might be an usecase with errors (too be clarified)

![image](https://user-images.githubusercontent.com/632221/68762591-c4dbae80-0616-11ea-8087-705c74d3d393.png)
