### ISSUE TITLE
Return from the metrics

### ISSUE THREAD

**Issue by witekw** [TouK/nussknacker#337]
![image](https://user-images.githubusercontent.com/632221/68485903-55457800-0240-11ea-80cd-ddaea2b1b2db.png)

If you open metrics from process list of from inside of a process, arrow as shown above is displayed. Clicking on it gets you to the process visualisation i.e. a different place if you navigated from the process list.

It might be connected to #188.

**Comment by lciolecki** [comment]
Connected with https://github.com/TouK/nussknacker/issues/238

**Comment by lciolecki** [comment]
Resolved in #1188
