### ISSUE TITLE
Issues running Nussknacker start and stop scripts on MacOs

### ISSUE THREAD

**Issue by InsideTheo** [TouK/nussknacker#3522]
## 📚 Documentation

Hello,

I faced the issue of not being able to run the start.sh and stop.sh scripts from the get-started repository. That is because they use the commands realpath and sed, which do not exist on Mac. I replaced realpath with readlink -f and sed with gsed (after installing it via brew), then it worked like a charm. Maybe you could change it so it works on Mac too per default, document how it can be run on Mac or state somewhere that the code is not meant to run on a mac?

Kind regards

**Comment by arkadius** [comment]
Thank you for feedback. This commands will be available after installing `coreutils` package - no changes in scripts are required. I've just added mention about this additional step for MacOS users in quickstart repo: https://github.com/TouK/nussknacker-quickstart/pull/95/files . Is it ok for you?

Regards,
Arek

**Comment by InsideTheo** [comment]
Of course, very good! Thanks for the quick response :)
