### ISSUE TITLE
Disable paste button (if possible) when content invalid for NK graph is in the clipboard

### ISSUE THREAD

**Issue by witekw** [TouK/nussknacker#362]
- It should not be necessary to show "Paste button is not available. Try Ctrl+V"
- copy paste of text data should be tested in regular input boxes

**Comment by PPiedel** [comment]
It is not possible if we use system clipboard due to security reasons.
Should we use Redux's store? If so, then copying nodes between windows would be not possible, which is most common use case of nodes copying.

**Comment by mproch** [comment]
Won't do...
