### ISSUE TITLE
Node's subtype should be visible near nodes title

### ISSUE THREAD

**Issue by arkadius** [TouK/nussknacker#374]
Currently node's "subtypes" like reftype in source/sink and service id in service is visible as a reaonly field.

As a user I'd rather want to see it near modal's title - next to source/sink/processor.

**Comment by fi-** [comment]
should look like this:
![modaltop-1](https://user-images.githubusercontent.com/8850099/69424504-137cfd00-0d29-11ea-973c-d737427a6c92.jpg)
![modaltop-2](https://user-images.githubusercontent.com/8850099/69424507-17108400-0d29-11ea-9e6f-199081004e9b.jpg)

height: 30px
text color: #f2f2f2
background color of subtype: #3a3a3a
