### ISSUE TITLE
Build Error: while running C:\NusskNacker\staging\nussknacker-staging\designer\runServer.sh

### ISSUE THREAD

**Issue by pokkireddy** [TouK/nussknacker#3954]
Build Error: while running C:\NusskNacker\staging\nussknacker-staging\designer\runServer.sh

Attached the log file for your reference. please let me know what is missed. 

**Environment (please fill in the following information):**
 - OS:  Ubuntu 18.04.6 LTS
 - Nussknacker version [staging]
 - Flink version
 - Java version:
 -openjdk 17.0.6 2023-01-17
  OpenJDK Runtime Environment Temurin-17.0.6+10 (build 17.0.6+10)
  OpenJDK 64-Bit Server VM Temurin-17.0.6+10 (build 17.0.6+10, mixed mode, sharing)
 - Scala version
 - Method of running of components [e.g. in Docker, lite, flink]
[](url)
[runServer.sh.log](https://github.com/TouK/nussknacker/files/10504850/runServer.sh.log)

**Comment by gadomsky** [comment]
Hi @pokkireddy, thanks for reporting a issue. Looks like you're build is missing devModel (`<repo dir>/nussknacker-dist/target/universal/stage/managers/development-tests-manager.jar`)

If you build source using our scripts as described in Readme https://github.com/TouK/nussknacker/blob/staging/CONTRIBUTING.md#running-full-version-of-designer-from-command-line
 everything should work.
 
So in summary, the order of operations is as follows:
 * cloning fresh repo from repository
 * cd designer
 * ./buildClient.sh
 * ./buildServer.sh (please notice, that this script sets flag `addDevArtifacts` to `true` - I think, this is what you were missing) 
 * ./runServer.sh
 
 Please try to execute this instructions, and let us know if it had worked for you :)

**Comment by pokkireddy** [comment]
[runServer_Error.txt](https://github.com/TouK/nussknacker/files/10510495/runServer_Error.txt)

I have followed the same steps, still getting error. 
I can able to see this jar ( (<repo dir>/nussknacker-dist/target/universal/stage/managers/development-tests-manager.jar) attached in the log at the end.

Please find the attached log.

My use case is I want to change some UI text for ex: Instead of scenarios we would to like to change something else
and build a docker image from this. Please let me know the steps for that.

**Comment by pokkireddy** [comment]
Based on the fix, I can able to runServer.sh without any error.

My use case is I want to change some UI text for ex: Instead of scenarios we would to like to change something else
and build a docker image from this. Please let me know the steps for that. Do we have docker file to generate image ?

**Comment by gadomsky** [comment]
Great :) This fix will problably be optimized a little bit before merge, but feel free to used it for now.

Docker images are built with [sbt native-packager plugin](https://www.scala-sbt.org/sbt-native-packager/formats/docker.html), so there is no dedicated Dockerfile in our codebase. The usage is straightforward:
 * `sbt dist/Docker/publishLocal` to publish it locally 
 * or `sbt dist/Docker/publish` to publish to remote docker registry, but please remember to set environment variables `dockerUserName` and `dockerPackageName` pointing to your remote registry. 
You can also provide own tag for you image with `dockerTagName` environment variable.

Can you please also tell us more about your usecase for Nusskancker? And also whether you use Flink or Lite Engine for Nusskancker runtime?

**Comment by pokkireddy** [comment]
Could you please provide some steps like from which path to run the command "sbt dist/Docker/publishLocal".
I just executed the ./buildClient.sh ,./buildServer.sh,./runServer.sh 
after that if i run above sbt docker command it throws error
[sbt_docker_plugin.txt](https://github.com/TouK/nussknacker/files/10520254/sbt_docker_plugin.txt)
also it shows "development environment" in UI. How to build and publish in production mode ?

We have an existing k8s environment which we have to use Nussknacker with flink for datamapping and decision making.

**Comment by gadomsky** [comment]
Scripts inside `desinger` are meant for local development. 
`sbt dist/Docker/publishLocal` should be executed from root dir and it results in production build. 
Label in the UI is [configurable](https://nussknacker.io/documentation/docs/installation_configuration_guide/DesignerConfiguration#environment-configuration)
If you have more questions about Nussknacker feel free to book an appointment with us https://calendly.com/nussknacker/support
In a meantime, you can also star the project if it's interesting for you.

**Comment by pokkireddy** [comment]
[nussknacker-docker-image-update-notworking.docx](https://github.com/TouK/nussknacker/files/10521863/nussknacker-docker-image-update-notworking.docx)


Thanks for your prompt response and details.
I have updated the document with the steps what i did. could you please check why the latest docker image

**Comment by gadomsky** [comment]
`staging` branch is our development branch, it might be not stable, but first of all it's not tested agianst other projects (like `nusskancker-helm`, `nussknacker-quicstart` and others). Those project are tested only with stable version, which is branch `master`. Please try to fork that branch, not staging, and try again.

* git checkout master
* addDevArtifacts=true  sbt "dist/clean; buildClient; dist/Docker/publishLocal"

Also, please remember to pass flag `NO_PULL=true` when running `./start.sh` in quickstart, because without it, the script pulls image from remote-registry, which in your case overrides your locally built image.

**Comment by pokkireddy** [comment]
I am getting some error while executing this command 
addDevArtifacts=true sbt "dist/clean; buildClient; dist/Docker/publishLocal"

Please find the log file
[buildServer_Error.txt](https://github.com/TouK/nussknacker/files/10549682/buildServer_Error.txt)

**Comment by gadomsky** [comment]
I have checked again, and on my local machine following steps produce successful dockerimage:

```
git clone git@github.com:TouK/nussknacker.git
cd nussknacker
git checkout master
addDevArtifacts=true sbt "dist/clean; buildClient; dist/Docker/publishLocal"
```

* btw. I use java 11 when building, I can see that you're usiing java17, but I dont think it's the case
* do you obtain the same error when executing this on branch master without any modification of yours? 
* and without executing any prior commands?

**Comment by pokkireddy** [comment]
i have not modified anything and followed the above steps, still getting error. please find the 
[build_eror_1FEB.txt](https://github.com/TouK/nussknacker/files/10558468/build_eror_1FEB.txt)
log

**Comment by gadomsky** [comment]
> btw. I use java 11 when building, I can see that you're usiing java17, but I dont think it's the case

looks like java version it is. I have run the build against java17 and got the same error as you do. Please use java11.

**Comment by pokkireddy** [comment]
I have installed java11 and tried build is success. I see the error (At the end) while generating docker image but i think this is not actual error. Please check the logs and confirm. 
[Build_Details_2-FEB.txt](https://github.com/TouK/nussknacker/files/10573348/Build_Details_2-FEB.txt)

**Comment by gadomsky** [comment]
On my local environment, logs look slightly different. But the last two lines of your logs indeed make an impression that the whole build is successful. Please confirm it on your own, that it's ok, by runing this docker image and seeing if everything is ok.

**Comment by pokkireddy** [comment]
I can able to run the docker image locally without any issue.
Now i am trying in azure cloud aks environment mode using this link https://nussknacker.io/documentation/quickstart/helm
Please see the errors in the attached document and let me know how to resolve these. we will be using in K8s only.
[Nussknacker_k8s_Error.docx](https://github.com/TouK/nussknacker/files/10593733/Nussknacker_k8s_Error.docx)

**Comment by gadomsky** [comment]
You have probably imported this https://github.com/TouK/nussknacker-quickstart/blob/main/docker/streaming/scenarios/DetectLargeTransactions.json scenario to your Nussknacker which is meant for Flink engine. Please import that one https://github.com/TouK/nussknacker-quickstart/blob/main/k8s-helm/scenarios/DetectLargeTransactionsLite.json
They differ in `typeSpecificData` filed whic is engine-specific.

**Comment by gadomsky** [comment]
![image](https://user-images.githubusercontent.com/15062439/216998347-c3078b26-0e3a-4aae-8c23-13001fe68a66.png)
![image](https://user-images.githubusercontent.com/15062439/216998385-63e1688a-07e2-4bad-9f2d-5dae0dafbe38.png)
Please verify you have correct configuration of liveness and readiness for your akhq deployment

**Comment by pokkireddy** [comment]
I have tried loading https://github.com/TouK/nussknacker-quickstart/blob/main/k8s-helm/scenarios/DetectLargeTransactionsLite.json it is working.
Regarding liveness and readiness probe i have changed the config as per attached document and it is running (please confirm the path is correct). But facing one issue while clicking on schema tab.
[akhq.docx](https://github.com/TouK/nussknacker/files/10670220/akhq.docx)

**Comment by pokkireddy** [comment]
Regarding docker image command question after i executed the below command and using this image. The data tab is not displayed.
 addDevArtifacts=true sbt "dist/clean; buildClient; dist/Docker/publishLocal"

![Docker_Build](https://user-images.githubusercontent.com/63649118/217116688-5f1b42ff-9654-4739-b358-fb682da469e2.JPG)

**Comment by gadomsky** [comment]
It's not matter of docker image, but configuration. Additional tabs can be configured in your Helmchart using `.Values.nussknacker.customTabs`. Api for configuring main menu tabs is described here https://nussknacker.io/documentation/docs/installation_configuration_guide/DesignerConfiguration/#main-menu-configuration

Alternatively you can use a lot more powerful approach, but a little bit more complicated. Provide secret or configMap with separate configuration file  `application.conf` for Nussknacker (this way you can override any Nusskancker configuration), then mount it to you deployment (it's not desribed yet in the docs but you can figure it out from our helm source code. Basically you do it like in normal K8 deployment :
https://github.com/TouK/nussknacker-helm/blob/main/src/templates/deployment.yaml#L50
https://github.com/TouK/nussknacker-helm/blob/main/src/templates/deployment.yaml#L131
)
And then  pass it to Nusskacker with Values `nussknacker.configFile: <path_to_exisiting_application_conf>,<you_mounted_application_conf_file>` (https://artifacthub.io/packages/helm/touk/nussknacker#configuration) 
Since Nusskancker accepts multiple configuration files, you can place only configurations that you want to add/override in your file, and pass your file along with default configuration file.
