### ISSUE TITLE
List of processes does not fill all available space

### ISSUE THREAD

**Issue by witekw** [TouK/nussknacker#399]
![image](https://user-images.githubusercontent.com/632221/69228391-c7448800-0b83-11ea-8e57-9a90e4ca570a.png)

Page has always 10 elements. It should be more when there is space, it should be less if there is no space to prevent scroll. It would require calculation and update of table compoenent properties.

**Comment by PPiedel** [comment]
I'm not sure if this is a good idea.
We should consider pagination. It is a common way to solve this kind of issues: https://material.io/components/data-tables/#behavior

**Comment by witekw** [comment]
It should always look good i.e. without the space below the table. https://www.npmjs.com/package/react-table for example has minRows parameter and fills the table with empty rows when necessary.

**Comment by witekw** [comment]
I think there's ongoing redesign of it. @fi- ?
