### ISSUE TITLE
deploy error when following the first  example   

### ISSUE THREAD

**Issue by pgibert** [TouK/nussknacker#4]
Hello
run with docker compose it works for me up to  the Save ( first process )  

when i deploy the saved process  i got an error    in the docker logs 
**app_1            | org.apache.flink.util.ConfigurationException: Config parameter 'Key: 'jobmanager.rpc.address' , default: null (deprecated keys: [])' is missing (hostname/address of JobManager to connect to)** 
 it seems related to 
 environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager  in the docker  compose file ......  ? right ?
one setting  is lacking ? 

best regards 
philg

**Comment by fijolekProjects** [comment]
Thanks for letting us know. We fixed this issue. Please let us know if it works now
