### ISSUE TITLE
#this variable and it's content is not suggested in nested projection/filtering expression

### ISSUE THREAD

**Issue by raphaelsolarski** [TouK/nussknacker#4073]
**To Reproduce**
1. Create variable node with var name `foo` and following expression `{innerList: {{innerInnerList: {{a: 1, b: '2'}}}}}`
2. Create downstream variable node with expression like `#foo.innerList.![#this.innerInnerList.![#this]]`
3. Try to use autocompletion after usage of the second `#this` expression

<img width="794" alt="Screenshot 2023-03-06 at 18 47 25" src="https://user-images.githubusercontent.com/12599369/223189953-366d727b-b532-4c25-a8b2-524ddb61a5bb.png">

**Environment (please fill in the following information):**
 - Nussknacker version 1.8.1

**Comment by bartektartanus** [comment]
This is fixed in #4323 
<img width="941" alt="image" src="https://github.com/TouK/nussknacker/assets/3193882/b272ce30-2222-4317-9ebb-83150ae78157">
