### ISSUE TITLE
invalid node id validation

### ISSUE THREAD

**Issue by witekw** [TouK/nussknacker#414]
Testing on staging. 
Clicking "SAVE" on node details with invalid id e.g. "." character.

ProcessValidation returns text/plain, status 400 and payload of "Node id contains invalid characters:", . and ' are not allowed in node id". Error is reported in a Notification window.

When loading a process with an invalid node id (i'm not sure how it was saved) error is returned properly.

![image](https://user-images.githubusercontent.com/632221/69501038-411c9e80-0f01-11ea-8849-5168bace255f.png)

BTW - we should consider changing "SAVE" in details modals to "CONFIRM" and introducing client side validation of node ids.

**Comment by witekw** [comment]
One more thing. When processValidation fails with status 400, errors dissapear from the tip-panel.

**Comment by mproch** [comment]
It's regression... This error should prevent Save close modal window...

**Comment by witekw** [comment]
text/plain and status 400 is the regression? I have not seen preventing "SAVE" in any case before.

**Comment by mproch** [comment]
@witekw @PPiedel  https://github.com/TouK/nussknacker/pull/88/files#diff-48e3c6025347f57cdc820688e44f62e5L312 ==> this is when it stopped working.   Promise.reject(error) disappeared
