### ISSUE TITLE
nodeValidation endpoint for quick check of edited nodes/edges in the background

### ISSUE THREAD

**Issue by witekw** [TouK/nussknacker#426]
Currently we have ValidationResources and `processValidation` resource inside.
We should also have `nodeValidation` resource which will take:
- validation context on entering to node (types of variables)
- node (NodeData)

**Comment by witekw** [comment]
If possible, first create interface and basic logic endpoint for the frontend to integrate with.

**Comment by witekw** [comment]
It can be tricky, if a nodeValidation validates less than the processValidation. It would be not clear if a node passed a nodeValidation or just some validation was not run.

**Comment by lciolecki** [comment]
@mateuszkp96  what is a status this issue?

**Comment by mproch** [comment]
Already implemented
