### ISSUE TITLE
search button/label in process list is useless and should be just be a small icon

### ISSUE THREAD

**Issue by fi-** [TouK/nussknacker#434]
Since this is not a button you actually click I suggest changing the field to look like this:
<img width="243" alt="Asset 4@2x" src="https://user-images.githubusercontent.com/8850099/69646489-34668a80-1068-11ea-9645-b76d906f20ae.png">
the icon should turn blue when filtering is applied

**Comment by lciolecki** [comment]
It's already changed at staging - new design at process list.
