### ISSUE TITLE
Creating process without name

### ISSUE THREAD

**Issue by lciolecki** [TouK/nussknacker#489]
When I create process without name system throw error 404 , because route path doesn't exist. We shouldn't allow to create process without name and category ( Releated to #318 ). In fact we should throw error 400 - I mean that we should also refactor API to:
`POST /api/processes`
```
{
"name": "", //required not empty string 
"category": "", //required string from allowed categories..
"isSubrocess: false //by default false
}
```

**Comment by arkadius** [comment]
Minor bug after some improvements in handling this case that were done already. Closing
