### ISSUE TITLE
Error running docker-compose up

### ISSUE THREAD

**Issue by jose1003** [TouK/nussknacker#49]
**Describe the bug**
Kibana dont start
Grafana dont start

**To Reproduce**
Pull the project
docker-compose up -d

see the status
docker-compose ps

kibana and grafana are not working

**Expected behavior**
kibana and grafana must to work

**Screenshots**

**Environment (please complete the following information):**
Centos 7
Last version of project

How to fix the error(in my enviorement)

kibana:
there is in error in the docker-compose.yaml file

This line :       ELASTICSEARCH_HOSTS: httelasticsearch:9200
change to:       ELASTICSEARCH_HOSTS: http://elasticsearch:9200/

Grafana
in the script runWithFlinkEspBoard.sh, 
the line ./run.sh "${@}" & are not working,
change to:  /run.sh "${@}" &

**Comment by lciolecki** [comment]
Thanks a lot for report this bug! I'v already created a PR: https://github.com/TouK/nussknacker/pull/52.
