### ISSUE TITLE
Invalid end error is presented as "Errors IN ..." on the left panel

### ISSUE THREAD

**Issue by arkadius** [TouK/nussknacker#496]
The problem is in word "IN" the problem is not inside node, but the node is a problem. One solution for that could be excluding this type of error from grouping in "Errors in ..."

**Comment by PPiedel** [comment]
How to reproduce this kind of error?

**Comment by lciolecki** [comment]
Leave only source node in graf :)

**Comment by witekw** [comment]
"loose nodes: "
