### ISSUE TITLE
Editor for boolean type

### ISSUE THREAD

**Issue by arkadius** [TouK/nussknacker#504]
We need to have editor for boolean type.
IMO:
- should be possible to switch between human-friendly editor and expressions (like in grafana)
- editor should be accessible for all fields with type: java.lang.Boolean, also for expressions in filters or switches
- editor should be by default in "expression" mode
- if expression saved in process have either true or false, we should render it using boolean editor. Otherwise (e.g. `#input.foo`) we should use "expression" mode
- default editor can be changed on backend side (will be done in other task)

**Comment by witekw** [comment]
"expresion mode" editor should include expression's inferred type, what do you think? #249

**Comment by fi-** [comment]
![_input-mode-switch_1](https://user-images.githubusercontent.com/8850099/70982893-1c5ab780-20b8-11ea-91f1-6cf87141ddbe.png)
![_input-mode-switch_2](https://user-images.githubusercontent.com/8850099/70982894-1c5ab780-20b8-11ea-84e2-ea7afc211afd.png)

I am not sure about the naming of these modes. I prefer the classic advanced/simple

**Comment by fi-** [comment]
alternative, less eye-catching version with bg color #999999:
![_input-mode-switch_3](https://user-images.githubusercontent.com/8850099/70984335-93914b00-20ba-11ea-8312-0460d3b913a2.png)

**Comment by fi-** [comment]
![_input-mode-switch-crop_v2](https://user-images.githubusercontent.com/8850099/70992576-47e69d80-20ca-11ea-8933-473514d5d57a.gif)
icon is here:
[expression-mode.zip](https://github.com/TouK/nussknacker/files/3973074/expression-mode.zip)
icon field and the icon should both be 35x35px, icon is exported with padding
inactive icon color: #4d4d4d
active icon color: #8fad60
margin between icon field and input field should be 5px
