### ISSUE TITLE
Add react error boundaries

### ISSUE THREAD

**Issue by witekw** [TouK/nussknacker#507]
I would be good to prevent gui from being totaly unusable in case of an error. I see two candidates for it:

- subprocess graph embedded in node details modal
- node datails modal itself

We could render some details about environment for user to copy and report her problem.

https://reactjs.org/docs/error-boundaries.html

**Comment by lciolecki** [comment]
@fi-  we need some design for it - how to present that kind of information.

**Comment by arkadius** [comment]
Already done.
