### ISSUE TITLE
Details modal for grouped nodes should be editable

### ISSUE THREAD

**Issue by arkadius** [TouK/nussknacker#513]
Or if it cause some problems with validations, there should be at least some buttons to navigate to edition of concrete nodes.

**Comment by PPiedel** [comment]
I would rather add button to navigate to edition of concrete nodes

**Comment by PPiedel** [comment]
We need design for this. Maybe we should just link the name of the node to it's details? @fi- WDYTAT?

**Comment by arkadius** [comment]
Grouping feature needs rethinking. Closing
