### ISSUE TITLE
Make matomo works with matomo.cloud (cors)

### ISSUE THREAD

**Issue by arkadius** [TouK/nussknacker#529]
Currently we are using https://github.com/matomo-org/matomo-nodejs-tracker . It is desired to use on backend side. This causes cors error on Firefox.

We should implement (or use ready solution) with dynamic image loading: https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_enabled_image

Or expose in backend proxy to cloud version.

**Comment by PPiedel** [comment]
After analysis it turned out that in fact it works even right now.
