### ISSUE TITLE
Not editable properties in archived process should be visible (readonly)

### ISSUE THREAD

**Issue by arkadius** [TouK/nussknacker#572]
Currently they are hidden:

![image](https://user-images.githubusercontent.com/534341/71963077-270df580-31fb-11ea-9fb9-b77f0196764f.png)

and it is confusing. Should be visible but readonly instead. Readonly should be distinguishable which is more general problem (they are sometimes not): #192

**Comment by PPiedel** [comment]
Maybe it could look like this?
![Screenshot from 2020-01-08 11-50-20](https://user-images.githubusercontent.com/9641011/71972618-4a41a080-320d-11ea-9bc1-b3a4373cc6bf.png)

**Comment by arkadius** [comment]
There are still problems:
- checkboxes not change background
- simple/raw editor switcher not changes style
- some other fields not changes style: description, some other fields in compare
