### ISSUE TITLE
Select list in node edit has unnecessary padding

### ISSUE THREAD

**Issue by fi-** [TouK/nussknacker#581]
![2020-01-09 09_51_53-Nussknacker](https://user-images.githubusercontent.com/8850099/72052852-2ee69c00-32c6-11ea-96f9-c7953f8b7f2f.png)

**Comment by Crack** [comment]
And hovered arrow of expanded list is almost invisible: ![obraz](https://user-images.githubusercontent.com/1409807/90511849-6d4a1080-e15d-11ea-86f2-0e66b4c82945.png)
