### ISSUE TITLE
To many envrionment labels in "Versions" section

### ISSUE THREAD

**Issue by gadomsky** [TouK/nussknacker#586]
**Describe the bug**
To many envrionment labels in "Versions" section. Only those that map to DeploymentAction("DEPLOY") status should appear.

**To Reproduce**
deploy process,
cancel process,
deploy process

**Environment**
 - Nussknacker version master

![bug](https://user-images.githubusercontent.com/15062439/72090094-9e33ae80-330d-11ea-8c15-81ffcdd077b7.png)

**Comment by mproch** [comment]
This also breaks healthChecks - if process is deployed and then cancelled then we display it as "should be running"

**Comment by gadomsky** [comment]
@lciolecki this issue still occures
