### ISSUE TITLE
Changing number of seconds in DatePicker results in FE crush.

### ISSUE THREAD

**Issue by gadomsky** [TouK/nussknacker#587]
**Describe the bug**
Changing number of seconds to **00** results in whole FE application crush. 

**To Reproduce**
* Open **process edit** view and **counts** modal in **Tests** section 
* Click **Last hour** 
* Ensure that number of seconds is different than **0**
* Highligth number of seconds with mouse
* Change it by keyboard to **00**
* Click somewhere
* BUM 

**Environment**
 - Nussknacker version MASTER

**Comment by lciolecki** [comment]
Realted with #718

**Comment by mproch** [comment]
Closed with #896
