### ISSUE TITLE
Improvements styles consistency 

### ISSUE THREAD

**Issue by fi-** [TouK/nussknacker#593]
![2020-01-13 11_17_34-Nussknacker](https://user-images.githubusercontent.com/8850099/72247997-6622b900-35f6-11ea-8ed8-c421cccf09e0.png)
a couple of things to fix in subprocess input definintion:
1) selects should also have a subtle outline just like other input fields
2) "+" button should actually look like a "+", and "-" button should be centered, now it's going towards bottom
3) "+" button should be aligned to left. Remove unneccesary margin
![2020-01-13 11_25_19-Nussknacker](https://user-images.githubusercontent.com/8850099/72248416-68394780-35f7-11ea-8d31-7d3468198092.png)
4) remove unneccesary border from selects' list elements
5) on the right side of the list there is a thin white vertical line just next to scroll bar that we need to get rid of

and another consistency problem in map variable:
![2020-01-13 11_28_24-Nussknacker](https://user-images.githubusercontent.com/8850099/72248627-e8f84380-35f7-11ea-980d-fc57264f669a.png)
6) ace editor fields have 37px height, they should be the same as other text input fields - 35px height

also a minor issue related to this in nodes where switching between basic/expression mode is possible in certain fields:
![2020-01-13 11_31_43-Nussknacker](https://user-images.githubusercontent.com/8850099/72248871-78055b80-35f8-11ea-94b0-87e9fef73c77.png)
7) the switch button should have subtle outline

**Comment by Crack** [comment]
![obraz](https://user-images.githubusercontent.com/1409807/77312360-2406a980-6d02-11ea-8a95-ce886d4e580a.png)

Also, list should be next to <select> field, without this large margin, and should be visually distinct from background.

**Comment by lciolecki** [comment]
It's already done.
