### ISSUE TITLE
Saving node with name used by other node results in FE crush.

### ISSUE THREAD

**Issue by gadomsky** [TouK/nussknacker#598]
**Describe the bug**
Saving node with name used by other node results in FE crush.

**To Reproduce**
* create with valid process with nodes with names: A and B
* edit node A and set it's name to B 
* click save

Related with https://github.com/TouK/nussknacker/issues/592

**Comment by witekw** [comment]
Looks like a place for a new validator.

**Comment by mproch** [comment]
Closed via #948
