### ISSUE TITLE
can not use other sink name, eg: 'othersEvents' instead of 'processedEvents'

### ISSUE THREAD

**Issue by MicDP** [TouK/nussknacker#6]
unable to parse line: demo.65a1e1357e55.taskmanagerTask.3bc122984b5b029b7b8dd8b529e9a39e.DetectLargeTransactions.Source:-DetectLargeTransactions-source.0.KafkaConsumer.heartbeat-response-time-max -Infinity 1524734472: field "demo.65a1e1357e55.taskmanagerTask.3bc122984b5b029b7b8dd8b529e9a39e.DetectLargeTransactions.Source:-DetectLargeTransactions-source.0.KafkaConsumer.heartbeat-response-time-max" value: "-Inf" is unsupported

**Comment by fijolekProjects** [comment]
Hi, these logs are some metric errors that seems irrelevant to your problem.
Try to list kafka topics. You can use command:
`docker exec -i docker_kafka_1 "/opt/kafka_2.12-0.10.2.1/bin/kafka-topics.sh" --list --zookeeper zookeeper:2181`

Example:
````
12:40 $ docker exec -i docker_kafka_1 "/opt/kafka_2.12-0.10.2.1/bin/kafka-topics.sh" --list --zookeeper zookeeper:2181
__consumer_offsets
othersEvents
processedEvents
transactions
````
You can see what's in kafka topic with command:
`docker exec -i docker_kafka_1 "/opt/kafka_2.12-0.10.2.1/bin/kafka-console-consumer.sh" --topic othersEvents --bootstrap-server kafka:9092 --from-beginning --timeout-ms 1000`

Example:
```
12:44 $ docker exec -i docker_kafka_1 "/opt/kafka_2.12-0.10.2.1/bin/kafka-console-consumer.sh" --topic othersEvents --bootstrap-server kafka:9092 --from-beginning --timeout-ms 1000
{"eventDate":1524739022037,"amount":54,"clientId":"Client2"}
{"eventDate":1524739022172,"amount":30,"clientId":"Client1"}
{"eventDate":1524739022206,"amount":40,"clientId":"Client3"}
[2018-04-26 10:45:02,762] ERROR Error processing message, terminating consumer process:  (kafka.tools.ConsoleConsumer$)
kafka.consumer.ConsumerTimeoutException
	at kafka.consumer.NewShinyConsumer.receive(BaseConsumer.scala:90)
	at kafka.tools.ConsoleConsumer$.process(ConsoleConsumer.scala:120)
	at kafka.tools.ConsoleConsumer$.run(ConsoleConsumer.scala:75)
	at kafka.tools.ConsoleConsumer$.main(ConsoleConsumer.scala:50)
	at kafka.tools.ConsoleConsumer.main(ConsoleConsumer.scala)
Processed a total of 3 messages
```

**Comment by MicDP** [comment]
@fijolekProjects it's OK, Thanks.
