### ISSUE TITLE
BoolEditor getters gives undefined result when called from EditableExpression context

### ISSUE THREAD

**Issue by PPiedel** [TouK/nussknacker#624]
**Describe the bug**
BoolEditor switchableToHint and notSwitchableToHint are undefined when called from EditableExpression context

**Steps to reproduce**
1. Display simpleTypesService node from "types" category.
2. Switch to expression mode on "booleanParam".
3. Hover on switch icon should display "Switch to basic mode" or "Expression must be equal to true or false to switch to basic mode", but it displays nothing

**Comment by lciolecki** [comment]
This is already resolved.
