### ISSUE TITLE
'No configuration setting found for key 'kafka.zkAddress'

### ISSUE THREAD

**Issue by mspichalski** [TouK/nussknacker#63]
Hi,

I just cloned the repo and wanted to start working with the demo setup. Unfortunatelly I run in to a problem when adding a new process to Nussknacker:

 [ERROR] [06/19/2019 10:20:51.613] [nussknacker-ui-akka.actor.default-dispatcher-35] [akka.actor.ActorSystemImpl(nussknacker-ui)] Error during processing of request: 'No configuration setting found for key 'kafka.zkAddress''. Completing with 500 Internal Server Error response. To change default exception handling behavior, provide a custom ExceptionHandler.

I started looking for causes and found out that just 4 hours ago a commit was made:

"[CONFIG] - remove unused zkAddress config" by mproch
https://github.com/TouK/nussknacker/commit/f803ae39b050a7abe6f669c5c732ab85711bc94e

Could it be that zkAddress was used? 

Thanks,
Marek

**Comment by jackviewhigh** [comment]
encountered same issue here

**Comment by jackviewhigh** [comment]
@mspichalski After some digging, I think that commit fix the issue instead of introducing it. You just need to use lastest docker image, for example: "NUSSKNACKER_VERSION=latest docker-compose up".

**Comment by mspichalski** [comment]
@jackviewhigh Yeah, I figured it out. Changed the demo-latest to latest in docker-compose file. Issue closed :)
