### ISSUE TITLE
lots of warning for nussknacker_influxdb | [graphite] with value: "-Inf" is unsupported

### ISSUE THREAD

**Issue by jackviewhigh** [TouK/nussknacker#64]
**Describe the bug**

When using docker-compose up, granafa and elasticsearch works, but lots of warning emmited on console

**To Reproduce**

NUSSKNACKER_VERSION=latest docker-compose up

**Expected behavior**
No such warnings

**Screenshots**

![image](https://user-images.githubusercontent.com/50261348/59977591-7eed6200-9605-11e9-9b9c-68f6bb65531e.png)

**Environment (please complete the following information):**
 - OS: CentOS 7.5
 - Method of ran of components: in docker
 - Browser type and version: chrome 75

**Additional context**

* follow guide [here](https://github.com/TouK/nussknacker/blob/master/docs/Quickstart.md)

```
nussknacker_influxdb | [graphite] 2019/06/23 14:18:06 unable to parse line: demo.5751303fa6e6.taskmanagerTask.c404bf027acc1da660ee22d9f7812161.DetectLargeTransactions.Sink:-DetectLargeTransactions-save-to-elastic-sink.1.KafkaProducer.request-latency-max -Infinity 1561299486: field "demo.5751303fa6e6.taskmanagerTask.c404bf027acc1da660ee22d9f7812161.DetectLargeTransactions.Sink:-DetectLargeTransactions-save-to-elastic-sink.1.KafkaProducer.request-latency-max" value: "-Inf" is unsupported
```

**Comment by arkadius** [comment]
We have similar issue, adding in Flink's logback.xml helped:
```
        <filter class="ch.qos.logback.core.filter.EvaluatorFilter">
            <evaluator>
                <expression>
                <![CDATA[
                return level == WARN
                    && logger.equals("org.apache.flink.runtime.metrics.MetricRegistryImpl")
                    && throwable != null
                    && throwable.getMessage() != null
                    && throwable.getMessage().contains("∞");
                ]]>
                </expression>
            </evaluator>
            <OnMatch>DENY</OnMatch>
            <OnMismatch>NEUTRAL</OnMismatch>
        </filter>
```
Probably need some adoption for docker-compose configuration...

**Comment by lciolecki** [comment]
We should also update influxdb container..

**Comment by lciolecki** [comment]
We updated influx to 1.7. Now we don't have these problems.
