### ISSUE TITLE
Can not run from IntelliJ, refer to ‘https://github.com/TouK/nussknacker/tree/master/ui/server‘

### ISSUE THREAD

**Issue by MicDP** [TouK/nussknacker#7]
java.lang.IllegalArgumentException: ProcessConfigCreator not found. Jars found: file:/E:/gits/nussknacker-master/ui/server/../../engine/flink/management/sample/target/scala-2.11/managementSample.jar

**Comment by mproch** [comment]
Before running in Intellij you have to run:
./sbtwrapper managementSample/assembly
(not sure how you run sbt on windows though...)

We'll update https://github.com/TouK/nussknacker/blob/master/ui/server/README.md
to be more specific about this...

**Comment by MicDP** [comment]
@mproch Thank you! I have resolved it by running 'nussknacker' on Ubuntu.
