### ISSUE TITLE
Please update old images/videos in docs

### ISSUE THREAD

**Issue by fijolekProjects** [TouK/nussknacker#700]
...because sometimes I'm ashamed to show Nussknacker to other people ;)

**Comment by lciolecki** [comment]
Soon.. ;)

**Comment by arkadius** [comment]
We will do this, but currently we have two big redesigns on our shortlist: right panel will cover less graph's working space and process list will has dark theme just like other places do. Meantime I've upgraded demo available here: https://demo.nussknacker.io/ . Feel free to share this link with "other people" ;-)

**Comment by fijolekProjects** [comment]
Looks really cool :)

Things to improve:
 - In process view I have some error related to 'capabilites'
![nussknacer_error](https://user-images.githubusercontent.com/2931571/74772427-43885d80-5290-11ea-8fd0-a1b1258c3260.png)
- On first render of the app, there is some issue with lazy loading of tool icons, video: https://streamable.com/00m2r

**Comment by arkadius** [comment]
Thanks for warm words :) One killer feature is that user don't need to know ctrl+space for code completion anymore. It is not work perfect, but we are one step closer to be human friendly. There are also few hidden features for that we haven't prepared demo and docs yet - like dictionaries resolved on ui side using Elastic's full text search.

Regards to your issues:
- I already have a fix. Please give an approve: https://github.com/TouK/nussknacker/pull/705/files
- I've reported an issue: https://github.com/TouK/nussknacker/issues/704 . We will fix it soon.

Thanks for reporting!

**Comment by witekw** [comment]
I've updated images some time ago. Videos need update.

**Comment by dswiecki** [comment]
Will be done during documentation rework
