### ISSUE TITLE
Cannot add documentation for sqlVariable

### ISSUE THREAD

**Issue by alien11689** [TouK/nussknacker#723]
**Describe the bug**
When I try to configure `docsUrl` for node `sqlVariable` NK always shows documentation of node `variable` (if it is configured).
Additionally, to configure `mapVariable` I have to add `docsUrl` for node `variableBuilder`. It is not very intuitive and could cause problems in future

**To Reproduce**
1. Add nodes configuration to `processConfig`:
```
nodes {
   "variable" {
      docsUrl: "https://nussknacker.io/designingProcesses/BasicNodes.html#variable"
    }
    "variableBuilder" {
      docsUrl: "https://nussknacker.io/designingProcesses/BasicNodes.html#map-variable"
    }
    "sqlVariable" {
      docsUrl: "https://nussknacker.io/designingProcesses/BasicNodes.html#sql-variable"
    }
}
```
2. Create process with `sqlVariable` and `mapVariable`
3. Open `sqlVariable` or `mapVariable`
4. Check where node documentation link follows 

**Environment (please complete the following information):**
 - OS: Linux Mint 19
 - Nussknacker version [branch name]: `2020_02_24_14_36-staging-40fbcc29b78f6cde4d1d61810f66e196e6c636a6-SNAPSHOT`
 - Flink version: 1.9.2
 - Java version: 8
 - Scala version: 2.11
 - Method of ran of components: standalone on docker
 - Browser type and version: Chrome 79

**Comment by dswiecki** [comment]
Will be resolved after refactoring CustomNodes
