### ISSUE TITLE
Required / Mandatory String param 

### ISSUE THREAD

**Issue by lciolecki** [TouK/nussknacker#773]
For example configuration: 
```
class ValidatorTypesService extends Service with Serializable {
  @MethodToInvoke
  def invoke(@ParamName("email")
             @DualEditor(
               simpleEditor = new SimpleEditor(`type` = SimpleEditorType.STRING_EDITOR),
               defaultMode = DualEditorMode.SIMPLE
             ) email: String,
             @ParamName("age") @Nullable age: Int,
             @ParamName("birthday") @Nullable birthday: LocalDate,
             @ParamName("amount") @Nullable amount: BigDecimal,
             @ParamName("description") @Nullable description: String
            ): Future[Unit]
  = Future.successful(Unit)
}
```
Email field should be by default present as Simple Editor with Mandatory Validator but this looks like:
![required-string-param](https://user-images.githubusercontent.com/907665/76321164-e9ecdf00-62e1-11ea-9834-74d888679375.png)

Email should be marked as mandatory field after save..  And default value should be always set as null - now expression mode includes empty (`''`) content.

**Comment by arkadius** [comment]
It's not a bug :) Empty string is correct filled value. We need to introduce new NotEmptyValidator / NotBlankValidator. Take a look at this issue: https://github.com/TouK/nussknacker/issues/688

**Comment by lciolecki** [comment]
Okey, so I'm closing this PR.
