### ISSUE TITLE
Incorrect message while deploying proces

### ISSUE THREAD

**Issue by piotrp** [TouK/nussknacker#801]
Messages shown while process is being deployed:
![obraz](https://user-images.githubusercontent.com/1409807/76712881-e069d980-671c-11ea-9348-ca587c948933.png)

The green message says that deployment has been finished, while text under icon on top has old status for ~five more seconds. Looks like some race, I can't reliably repeat this.

Nussknacker version:
```
$ docker images | grep nuss
touk/nussknacker                                staging-latest      87b17f27a031        3 days ago          870MB
```

**Comment by mproch** [comment]
Partially resolved with #2203
