### ISSUE TITLE
Make ENTER key submit forms

### ISSUE THREAD

**Issue by piotrp** [TouK/nussknacker#823]
We can exit forms using ESC, so we should be able to submit them using ENTER.

**Comment by dswiecki** [comment]
@piotrp right now you can navigate with TAB on node details thus you can submit forms with you keyboard. ENTER is required in majority of the fields as you can enter complex expresions, maybe CTRL + ENTER would fit here nicely ?

**Comment by piotrp** [comment]
That would work too, so long as it's consistent throughout entire application
