### ISSUE TITLE
Date/Time field wrong date rendered

### ISSUE THREAD

**Issue by raphaelsolarski** [TouK/nussknacker#834]
**Describe the bug**
Wrong date/time representation in component (year part looks to be replaced by day and conversely).

**To Reproduce**
1. Create a component with datetime field
2. Open the component
3. Fill date/time in field (e.g. 01-03-2020 00:00) and click "Apply"
4. Open the component once again - date will be displayed wrong way:

![Screen Shot 2020-03-25 at 16 42 34](https://user-images.githubusercontent.com/12599369/77555557-a7b5c700-6eb7-11ea-81e2-24292ae63ddf.png)

**Environment (please complete the following information):**
 - OS: Mac OS
 - Nussknacker version: 2020_03_20_12_11-staging-3e43ed1ea86acfa8b45924cc1300c88158a756c2-SNAPSHOT
 - Flink version: 1.6.4
 - Java version: 1.8
 - Scala version: 2.11.12
 - Method of ran of components: custom runtime based on Flink
 - Browser type and version: Chrome 80.0.3987.149 (Official Build) (64-bit)

**Comment by mproch** [comment]
fixed in #836
