### ISSUE TITLE
Error on deleting month part in date/time field

### ISSUE THREAD

**Issue by raphaelsolarski** [TouK/nussknacker#835]
**Describe the bug**
Error on try to delete month part of date in date/time field

**To Reproduce**
1. Create a component with datetime field
2. Open the component
3. Fill date/time in field if not filled by default
4. Select month part in date and click backspace/delete
![Screen Shot 2020-03-25 at 16 53 48](https://user-images.githubusercontent.com/12599369/77556910-5f97a400-6eb9-11ea-9580-0590c190c4d6.png)
![Screen Shot 2020-03-25 at 16 53 56](https://user-images.githubusercontent.com/12599369/77556938-67574880-6eb9-11ea-817a-fdbe3b10bfbe.png)

**Environment (please complete the following information):**
- OS: Mac OS
- Nussknacker version: 2020_03_20_12_11-staging-3e43ed1ea86acfa8b45924cc1300c88158a756c2-SNAPSHOT
- Flink version: 1.6.4
- Java version: 1.8
- Scala version: 2.11.12
- Method of ran of components: custom runtime based on Flink
- Browser type and version: Chrome 80.0.3987.149 (Official Build) (64-bit)

**Comment by mproch** [comment]
fixed in #836
