### ISSUE TITLE
test-data redesign

### ISSUE THREAD

**Issue by fi-** [TouK/nussknacker#837]
This is how it looks right now:
![2020-03-26 12_40_39-Nussknacker](https://user-images.githubusercontent.com/8850099/77644066-c15f1900-6f60-11ea-9b97-83cabcf9b0dc.png)

And this is how we would like it to look:
![test-data_1](https://user-images.githubusercontent.com/8850099/77644080-c754fa00-6f60-11ea-92b2-b64865bd3760.png)

The main difference apart from aesthetics is the test case navigation. Currently we use a select field to choose a test case. In new design we have a panel on the left with a list of cases, making it easy to switch from one case to another. It should appear when a modal is opened. It should also remember the selected test case so that we can switch to a different node and still view test data for the same test case. If the test cases list is longer user should be able to scroll it.

colors:
background color for test-related ui: #32343d
background color for fields with test data and also for test case number in test cases panel on left: #3c3c47
border-color for fields (1px width), test-related ui (2px width) and separators in test-case list (1px width): #222222
background color for headings in test-related ui: #222222
background color for highliting selected test case: #454556
text color for almost all text: #b3b3b3
text color for test-data in fields: #cccccc

**Comment by dswiecki** [comment]
Will be done during test rework
