### ISSUE TITLE
Support for select box with null option

### ISSUE THREAD

**Issue by rafa-minimal** [TouK/nussknacker#843]
You can't set blank/null value on optional parameter with fixed values.

See "properties" > "fixedValueOptionalProperty "
https://staging.nussknacker.io/visualization/rgl?businessView=false

![chrome-capture](https://user-images.githubusercontent.com/30666431/77919190-28503b00-729d-11ea-8a5d-342dd41be452.gif)

Seen on current staging, chrome 80.

**Comment by rafa-minimal** [comment]
I've realized it can be worked around with additional explicit "blank" value.

```
editor values       mandatory     effect
"a", "b"            no            can't set blank/null
"blank", "a", "b"   no            ok
"blank", "a", "b"   yes           validation error 
```

![chrome-capture (1)](https://user-images.githubusercontent.com/30666431/77922010-c85b9380-72a0-11ea-8e95-fbf42c0ea9eb.gif)

I'm leaving it up to you, it seems counter intuitive, but it's a minor issue. 

Probably it would be easier to remove the concept of optional value from fixed values params and explicitly add blank if neeed.

**Comment by dswiecki** [comment]
Just as you described we support null option by adding 
```
val nullTopicOption: FixedExpressionValue = FixedExpressionValue("", "")
```
