### ISSUE TITLE
Invalid position of datepicker for DateTime paramter (basic parameter editor mode)

### ISSUE THREAD

**Issue by gskrobisz** [TouK/nussknacker#849]
When basic parameter editor is enabled for a DateTime parameter, a datepicker is shown at the bottom of the whole modal. Datepicker keeps being attached to the bottom regardless scrollbar position change.

See attached image.

**Environment (please complete the following information):**
https://staging.nussknacker.io
master
Firefox

![Zrzut ekranu z 2020-04-06 11-26-45_datepicker](https://user-images.githubusercontent.com/2381222/78545586-51704e80-77fc-11ea-9498-6a4ea91f4da2.png)

**Comment by dswiecki** [comment]
Already fixed
