### ISSUE TITLE
Broken node properties layout when using large property list

### ISSUE THREAD

**Issue by piotrp** [TouK/nussknacker#850]
1. Add a node with SPEL expression
2. Keep making it higher by adding new lines

Effect:
* Cancel and Apply buttons disappear
* we have a disconnected scrollbar over toolbar menu

Screenshot:
![obraz](https://user-images.githubusercontent.com/1409807/78546467-bf694580-77fd-11ea-8eeb-a91d178bd03f.png)

Firefox 74.0.1
Chrome 80
`window.devicePixelRatio == 1.25`

**Comment by mproch** [comment]
It works better now

**Comment by Crack** [comment]
Issue is still present:

- Firefox 83.0
- Chrome 87

**Comment by mproch** [comment]
It's not clear on which devices/under which conditions the problem appears...
