### ISSUE TITLE
Metrics screen: "go back to process" button is not distinctive

### ISSUE THREAD

**Issue by gskrobisz** [TouK/nussknacker#856]
On the Metrics screen the "go back to process" button is easily confused with "go to main page" link

![Zrzut ekranu z 2020-04-08 17-49-03](https://user-images.githubusercontent.com/2381222/78814410-de6b0180-79ce-11ea-858f-1100c61040aa.png)

**Comment by gskrobisz** [comment]
Se attached image:
red - "go back to process" button 
yellow - "go to main page" link

**Comment by gskrobisz** [comment]
Related to: https://github.com/TouK/nussknacker/issues/238

**Comment by lciolecki** [comment]
![preview](https://user-images.githubusercontent.com/907665/91972942-b41e3580-ed1b-11ea-958d-0331a34e17b6.jpg)

Button code: https://codepen.io/filipm1990/pen/abNLJma
