### ISSUE TITLE
Wrong error message for failed test from file

### ISSUE THREAD

**Issue by gskrobisz** [TouK/nussknacker#858]
Problem occurs when test from file fails. NK displays then an error message which is completly illegible gibber.

Usually happens when:
- proces has multiple nodes (>50 nodes)
- test file contains big load of data (>500 events)

See attached image:
![MicrosoftTeams-image](https://user-images.githubusercontent.com/2381222/78883230-80cfc700-7a59-11ea-96ac-69822337c17c.png)

**Comment by dswiecki** [comment]
Closing since test input is now limited
