### ISSUE TITLE
Problem with do Enters in StringEditor

### ISSUE THREAD

**Issue by lciolecki** [TouK/nussknacker#862]
**Describe the bug**
When some param has property StringEditor then at input control we can't do 'enter'. It creates some problem for example with add avro schema. Below you can see image:
![screenshot-staging nussknacker io-2020 04 16-12_24_21](https://user-images.githubusercontent.com/907665/79445629-43c97e80-7fdd-11ea-9fa8-db3e9e5a9479.png)

**Comment by Abrams27** [comment]
Solved by adding new editor (TextareaEditor) 
![Screenshot from 2020-05-19 13-10-14](https://user-images.githubusercontent.com/44381959/82332609-e82c4f80-99e5-11ea-8ad9-e07fbe61e8bc.png)
![Screenshot from 2020-05-19 13-11-18](https://user-images.githubusercontent.com/44381959/82332613-e8c4e600-99e5-11ea-9fa6-5a4f3803c0c2.png)
