### ISSUE TITLE
Problem with job status synchronization

### ISSUE THREAD

**Issue by gskrobisz** [TouK/nussknacker#925]
NK allows to deploy more than one instance of a process. It usually happens when deployment fails due to timeout: the deploy request fails but flink continues that deployment. Finally, the job is running with wrong NK status and an error message such as "There are some problems with process" or "Process has been canceled but still is running".

The source of the problem seems to be in synchronization between two sources of jobs status: flink and NK databse (see process_actions table). 

**Environment**
at customers env
v 0.1.0, branch master

**Comment by mproch** [comment]
closed via #927 and #930
