### ISSUE TITLE
Counts not detecting restarts properly (0.1.x)

### ISSUE THREAD

**Issue by arkadius** [TouK/nussknacker#980]
**Describe the bug**
After process restart there are presented negative values in counts.

From my investigation the problem is in `InfluxGenerator.detectRestarts`. it uses `source.count` metric which hasn't got proper values.
```
SELECT derivative(value) AS "derivative" FROM "flink"."autogen"."source.count" WHERE time > now() - 5h GROUP BY slot
```
returned no results. Correct query:
```
SELECT derivative(value) AS "derivative" FROM "flink"."autogen"."source.count.count" WHERE time > now() - 5h GROUP BY slot
```

**Environment (please complete the following information):**
 - Nussknacker version: 0.1.2

**Comment by lciolecki** [comment]
Resolved: https://github.com/TouK/nussknacker/pull/1127.
