### ISSUE TITLE
Automigrations mechanism for case when new parameters are added.

### ISSUE THREAD

**Issue by arkadius** [TouK/nussknacker#992]
Let's consider situation:
- Create process using some node
- Add parameter to this node definition
- Build model and restart nk with new model
- Go into created process
- Go into node

Expected behaviour:
Should be visible new parameter on parameters list with some value determined based on auto migration mechanism.

Current behaviour:
New parameter is not visible, error "Node parameters not filled" appear.

**Comment by dswiecki** [comment]
Was fixed with generic node transformation refactor
